In [2]:
import numpy as np
import pandas as pd 

df=pd.read_csv('customers.csv')
df

   customer_id        cust_name   occupation    income qualification
0             1     John Miller    Developer   20000.0         Btech
1             2     Mark Robert    Enginneer   40000.0         Btech
2             3    Reyan Watson   Scientists   60000.0           MSc
3             4     Shane Trump  Businessman   10000.0           MBA
4             5      Adam Obama      Manager   80000.0           MBA
5             6  Rincky Ponting    Cricketer  200000.0         Btech
6           NaN             NaN          NaN       NaN           NaN
7           NaN             NaN          NaN       NaN           NaN
8           NaN             NaN          NaN       NaN           NaN
9           NaN             NaN          NaN       NaN           NaN
10          NaN             NaN          NaN       NaN           NaN
11            ?             NaN          NaN       NaN           NaN

In [3]:
df.head()

  customer_id      cust_name   occupation   income qualification
0            1   John Miller    Developer  20000.0         Btech
1            2   Mark Robert    Enginneer  40000.0         Btech
2            3  Reyan Watson   Scientists  60000.0           MSc
3            4   Shane Trump  Businessman  10000.0           MBA
4            5    Adam Obama      Manager  80000.0           MBA

In [4]:
df.describe()

              income
count       6.000000
mean    68333.333333
std     69402.209379
min     10000.000000
25%     25000.000000
50%     50000.000000
75%     75000.000000
max    200000.000000

In [7]:
df.cust_name.fillna('Unknown', inplace=True)
df.cust_name
df.cust_name.isnull().sum()
df.cust_name.value_counts()
df.cust_name

C:\Users\Admin\AppData\Local\Temp\ipykernel_4976\650176222.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.cust_name.fillna('Unknown', inplace=True)

0        John Miller
1        Mark Robert
2       Reyan Watson
3        Shane Trump
4         Adam Obama
5     Rincky Ponting
6                NaN
7                NaN
8                NaN
9                NaN
10               NaN
11               NaN
Name: cust_name, dtype: str

In [ ]:
df.cust_name.fillna('Unknown', inplace=True)